### ISSUE TITLE
PHP warnings on first load of settings screen 

### ISSUE THREAD

**Issue by pippinsplugins** [skillfulplugins/rcp-avatax#1]
<img width="1705" alt="screen shot 2017-05-18 at 3 01 38 pm" src="https://cloud.githubusercontent.com/assets/1034109/26221110/fa977f4e-3bda-11e7-9955-ab19b1875218.png">

**Comment by tannerm** [comment]
Thanks @pippinsplugins! Just saw that you posted here and pushed a fix.
